AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - spec/spec_helper.rb
    - simplecov-lcov/**/*.rb
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - spec/lib/handler_spec.rb
    - spec/lib/core/manage_spec.rb
    - spec/lib/messages_spec.rb
    - spec/lib/factory/category_spec.rb