name: Linting

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - main
    paths:
      - 'lib/**/**/*.rb'
      - 'main.rb'
      - 'spec/**'
      - '.rubocop.yml'
      - 'Gemfile'
      - 'Rakefile'
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2"
      - run: bundle install
      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
